spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/learnsphere
    username: learnsphere_user
    password: learnsphere_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
