spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learnsphere
    username: postgres
    password: 3333
    driver-class-name: org.postgresql.Driver
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
