version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: learnsphere
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: 3333
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: pravinsonwane/learnsphere-backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/learnsphere
      SPRING_DATASOURCE_USERNAME: postgress
      SPRING_DATASOURCE_PASSWORD: 3333
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  frontend:
    image: pravinsonwane/learnsphere-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pgdata:
